#!/usr/bin/env bash
# .github/scripts/formula.sh
#
# Writes the Homebrew formula for a release to stdout, pointing it at that
# release's archives and the checksums built alongside them. The release
# workflow runs this and commits the result, so the formula is generated
# rather than kept in step by hand.
#
#   .github/scripts/formula.sh 0.1.0 dist/tnotify_0.1.0_checksums.txt

set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: ${0##*/} <version> <checksums-file>" >&2
  exit 2
fi

version="$1"
checksums="$2"

if [ ! -r "$checksums" ]; then
  echo "${0##*/}: cannot read $checksums" >&2
  exit 1
fi

# The sha256 sitting against one archive in the checksums file, which lists
# each as "<sha256>  <filename>".
sha_for() {
  local archive="$1" sha

  sha="$(awk -v want="$archive" '$2 == want || $2 == "./" want { print $1; found = 1 }
                                 END { exit !found }' "$checksums")" || {
    echo "${0##*/}: no checksum for $archive in $checksums" >&2
    exit 1
  }

  printf '%s' "$sha"
}

archive_for() {
  printf 'tnotify_%s_%s.tar.gz' "$version" "$1"
}

url_for() {
  printf 'https://github.com/karnull/tnotify/releases/download/v%s/%s' \
    "$version" "$(archive_for "$1")"
}

darwin_arm64_sha="$(sha_for "$(archive_for darwin_arm64)")"
darwin_amd64_sha="$(sha_for "$(archive_for darwin_amd64)")"
linux_arm64_sha="$(sha_for "$(archive_for linux_arm64)")"
linux_amd64_sha="$(sha_for "$(archive_for linux_amd64)")"

cat <<FORMULA
# Formula/tnotify.rb
#
# Generated by .github/scripts/formula.sh when a release is cut. Anything
# written here by hand is lost at the next release.

class Tnotify < Formula
  desc "Notifications and questions in a tmux popup, for panes nobody is watching"
  homepage "https://github.com/karnull/tnotify"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url_for darwin_arm64)"
      sha256 "$darwin_arm64_sha"
    end

    on_intel do
      url "$(url_for darwin_amd64)"
      sha256 "$darwin_amd64_sha"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for linux_arm64)"
      sha256 "$linux_arm64_sha"
    end

    on_intel do
      url "$(url_for linux_amd64)"
      sha256 "$linux_amd64_sha"
    end
  end

  def install
    bin.install "tnotify"
  end

  test do
    assert_equal "$version", shell_output("#{bin}/tnotify --version").strip
  end
end
FORMULA
